### ISSUE TITLE
Consider synchronizing version numbers runme <> runmejs

### ISSUE THREAD

**Issue by sourishkrout** [stateful/runmejs#2]
Follow up to: https://github.com/stateful/runme/issues/51

To make it super transparent what versions are running and their relationship.

**Comment by christian-bromann** [comment]
We have two options:

- pin runmejs versions to runme versions
    - __Advantage:__ transparent which runme version someone will download and use
    - __Disadvantage:__ doesn't give us much freedom, e.g. fixes to the JS lib have to wait until a new `runme` release
- have both maintain individual versions
    - __Advantage:__ freedom in individual releases for both
    - __Disadvantage:__ possible confusions which runme version is actually used

I tend towards the second solution and suggest to do our best making versions transparent, e.g. when calling

```sh
runme --version
```

to print something like

```sh
Runme NPM Wrapper v1.2.3
Runme Engine v3.2.1
```

An alternative would be to create release rules, e.g. runme cli only does major/minor semver bumps which would allow use to use patch bumps for runmejs fixes/updates.

Let me know what you think!

**Comment by christian-bromann** [comment]
This became obsolete as the new interface allows to provide a runme version for every command it exposes.
